runtime: python39

handlers:

  # Serve static files from the root directory
  - url: /static
    static_dir: static

  - url: /(.*\.(css|js))
    static_files: \1
    upload: (.*\.(css|js))

  - url: /.*
    static_files: index.html
    upload: index.html
    secure: always
