runtime: nodejs


automatic_scaling:
  min_instances: 1
  max_instances: 10
  cpu_utilization:
    target_utilization: 0.5
  target_concurrent_requests: 50

# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10